### ISSUE TITLE
[Windows] Build failed on 3.4.6 (working on 3.4.4)

### ISSUE THREAD

**Issue by EyalSi** [versatica/mediasoup#353]
Hi, 

On windows 10, Python 2.7.15,  the build is failing with version 3.4.6, but succeed with 3.4.4
The error we get - "error C2059: syntax error: ')'" - multiple times...

Please let us know if more information is required.
EyalS

**Comment by ibc** [comment]
Please, try to identify where such a error exactly happens.

**Comment by EyalSi** [comment]
thought you will anyhow run the build on windows... ;)

error C2146: syntax error: missing ')' before identifier 'PRIx64' it happens in ...\mediasoup\worker\deps\libsrtp\libsrtp.vcxproj

**Comment by ibc** [comment]
I don't have any Windows machine. I'd really ask people using mediasoup in Windows that, if you encounter a bug, please try to spot the issue as much as possible. I just cannot do it.

Regarding the error, no idea. Indeed I updated libsrtp yesterday to 2.3.0. However the only I changed in `libsrtp.gyp` is [this](https://github.com/versatica/mediasoup/commit/74cbc37783f5bcd710d846038563e14b625f053e#diff-263343a30e3c5683fef04dd6998fcf49L7). I do not see any mention to `PRIx64` and the only places where it appears in the code are those:

```
ibc at ibc-macbook-pro in ~/src/v3-mediasoup/worker/deps/libsrtp on v3
$ ack PRIx64
srtp/srtp/srtp.c
1672:    debug_print(mod_srtp, "estimated u_packet index: %016" PRIx64, *est);
1761:    debug_print(mod_srtp, "estimated packet index: %016" PRIx64, est);
1869:    debug_print(mod_srtp, "estimated u_packet index: %016" PRIx64, est);
2235:    debug_print(mod_srtp, "estimated packet index: %016" PRIx64, est);
2341:        debug_print(mod_srtp, "estimated packet index: %016" PRIx64, est);
2463:    debug_print(mod_srtp, "estimated u_packet index: %016" PRIx64, est);
```

Indeed this was changed in libsrtp 3 months ago:

https://github.com/cisco/libsrtp/blame/master/srtp/srtp.c (look for `PRIx64`).

I'll report it in libsrtp project. Please tell which Visual Studio version you are using and so on.

**Comment by ibc** [comment]
I've reported the issue in libsrtp here:

* https://github.com/cisco/libsrtp/issues/475

Please, comment on that issue by clarifying which Visual Studio version you are using.

**Comment by ibc** [comment]
BTW help @haiyangwu, is there something that can be done to make VS support `PRIx64`?

**Comment by haiyangwu** [comment]
VS already supports `PRIx64`,  and I add the snap code in our `main.cpp `, compile ok.  
```
int main(int argc, char* argv[])
{
	uint64_t val = 0x1234567890abcdef;
	printf("val = 0x%" PRIx64 "\n", val);

	// Ensure we are called by our Node library.
	if (std::getenv("MEDIASOUP_VERSION") == nullptr)
	{
		MS_ERROR_STD("you don't seem to be my real father!");

		std::_Exit(EXIT_FAILURE);
	}
       // ...
}
```

But .. for `libsrtp` Should add `#include <inttypes.h>` into it . 

> https://devblogs.microsoft.com/cppblog/c99-library-support-in-visual-studio-2013/
> https://stackoverflow.com/a/9225648

**Comment by ibc** [comment]
Thanks, @haiyangwu! So it seems that libsrtp already includes `<inttypes.h>` when make or cmake is used (somehow):

```
ibc at ibc-macbook-pro in ~/src/v3-mediasoup/worker/deps/libsrtp on v3
$ ack inttypes
srtp/crypto/include/integers.h
57:#include <inttypes.h>

srtp/config.hw
42:/* Define to 1 if you have the <inttypes.h> header file. */

srtp/configure.ac
149:    [unistd.h byteswap.h stdint.h sys/uio.h inttypes.h sys/types.h machine/types.h sys/int_types.h],

srtp/CMakeLists.txt
24:check_include_file(inttypes.h HAVE_INTTYPES_H)

srtp/configure
615:# include <inttypes.h>
4263:# On IRIX 5.3, sys/types and inttypes.h are conflicting.
4265:		  inttypes.h stdint.h unistd.h
4900:for ac_header in unistd.h byteswap.h stdint.h sys/uio.h inttypes.h sys/types.h machine/types.h sys/int_types.h

srtp/config_in.h
42:/* Define to 1 if you have the <inttypes.h> header file. */

srtp/config.h_win32vc7
43:/* Define to 1 if you have the <inttypes.h> header file. */

srtp/config_in_cmake.h
43:/* Define to 1 if you have the <inttypes.h> header file. */


ibc at ibc-macbook-pro in ~/src/v3-mediasoup/worker/deps/libsrtp on v3
$ ack PRIx64
srtp/srtp/srtp.c
1672:    debug_print(mod_srtp, "estimated u_packet index: %016" PRIx64, *est);
1761:    debug_print(mod_srtp, "estimated packet index: %016" PRIx64, est);
1869:    debug_print(mod_srtp, "estimated u_packet index: %016" PRIx64, est);
2235:    debug_print(mod_srtp, "estimated packet index: %016" PRIx64, est);
2341:        debug_print(mod_srtp, "estimated packet index: %016" PRIx64, est);
2463:    debug_print(mod_srtp, "estimated u_packet index: %016" PRIx64, est);
```

Since in mediasoup we use our own `worker/deps/libsrtp/libsrtp.gyp`, I assume we should define `HAVE_INTTYPES_H` into it **also** when in Windows, right? Right now we are not defining tons of macros when in Windows:

* https://github.com/versatica/mediasoup/blob/v3/worker/deps/libsrtp/libsrtp.gyp#L31

@haiyangwu can you add `HAVE_INTTYPES_H` in our `libsrtp.gyp` for Windows and help on which of those defines should also be added with in Windows?

**Comment by ibc** [comment]
IMHO we should check the new `BUILD.gn` that Chromium uses for libsrtp:

* https://chromium.googlesource.com/chromium/deps/libsrtp/+/master/BUILD.gn

**Comment by ibc** [comment]
Done in branch [issue-353](https://github.com/versatica/mediasoup/tree/issue-353). Relevant commit:

* https://github.com/versatica/mediasoup/commit/e53b4102030e46257686644544d982b8871b6092?ts=2

May you check it guys?

BTW: @haiyangwu is [this](https://github.com/versatica/mediasoup/commit/e53b4102030e46257686644544d982b8871b6092?ts=2#diff-4b28609e9309f6337d95f3683c624121L11) still true in VS? Otherwise we can get rid of the `config/config.h` file and define the  `PACKAGE_STRING` and `PACKAGE_VERSION` values directly in `libsrtp.gyp`.

**Comment by EyalSi** [comment]
Tested branch issue-353. build is successful and the server is starting.
THANKS!

**Comment by ibc** [comment]
Great, published in mediasoup 3.4.8.
